// Regenerated by scripts/gen-types.{sh,ps1} from apps/backend's OpenAPI schema.
// Do not hand-edit.

export * from "./generated";

export interface VaultManifestDTO {
  id: string;
  type: "VaultManifest";
  schema_version: number;
  app_version: string;
  created_at: string;
  migrations: { from: number; to: number; applied_at: string }[];
}

export interface VaultStatusDTO {
  open: boolean;
  manifest: VaultManifestDTO | null;
}
